package com.jackykeke.ownretromusicplayer.util

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import com.bumptech.glide.load.resource.bitmap.RoundedCorners
import com.jackykeke.ownretromusicplayer.R
import com.jackykeke.ownretromusicplayer.model.Song
import com.jackykeke.ownretromusicplayer.util.MusicUtil.getMediaStoreAlbumCoverUri

/**
 *
 * @author keyuliang on 2022/11/24.
 * @version 9999.0.0
 * @descrption 描述 ：
 * @copy 版权当然属于 keyuliang
 */
object AutoGeneratedPlaylistBitmap {

    fun getBitmap(context: Context,songPlayList:List<Song>?) :Bitmap?{

        if (songPlayList == null || songPlayList.isEmpty())
            return getDefaultBitmap(context)
        if (songPlayList.size == 1)
            return getBitmapWithAlbumId(context,songPlayList[0].albumId)

    }

    private fun getBitmapWithAlbumId(context: Context , id:Long): Bitmap? {

        return try {
            GlideApp.with(context)
                .asBitmap()
                .transform(RoundedCorners(20))
                .load(getMediaStoreAlbumCoverUri(id))
                .submit(200, 200)
                .get()
        } catch (e: Exception) {
            null
        }
    }
    private fun getDefaultBitmap(context: Context): Bitmap {
        return BitmapFactory.decodeResource(context.resources, R.drawable.default_album_art)
    }

}